name: CI
on:
  push:
  pull_request:
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Lint
        run: bash scripts/lint.sh
      - name: Typecheck
        run: bash scripts/typecheck.sh
      - name: Unit tests
        run: bash scripts/test_unit.sh
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            Tests/reports
